services:
  - type: web
    name: nostrpress
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: 'off'
    envVars:
      - key: NPUB
        sync: false
      - key: SITE_URL
        sync: false
